### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by lazybullfrog** [pulkomandy/spacewar#1]
R1B1, x86_64

g++-x86 -O3 -c -Wall -o engine.o Spacewar_3_1.cpp
make: g++-x86: Command not found
Makefile:15: recipe for target 'engine.o' failed
make: *** [engine.o] Error 127

**Comment by pulkomandy** [comment]
Yes, if you are not running a 32bit system you need to use gcc instead of gcc-x86.
I should probably use the makefile engine to abstract the details.

**Comment by lazybullfrog** [comment]
Compiles and runs great on 64 bit. Thanks for the update. I understand Makefiles a little better now.
